# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 25d55a83951dc7453a8e2bfb666131db129c9904e1b4e7bdcfad6f235ea75249265b066bd177fa0b2f9e10040746ce77354d76b0347251324abf80e6b21cd218

test:
  secret_key_base: 943af424be3bcdbbcbf1d2119656ad0a2e0a1f257047eb92dcc5db283959eb0fb1ff14be7442093f2278555afa3e3339387f5be88771646c420f812e772bb0c4

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
